# All notes for All saptak

sa_sudh_m = 'sound/SA.wav'
re_sudh_m = 'sound/RE.wav'
re_komal_m= 'sound/RE_K.wav'
ga_sudh_m = 'sound/GA.wav'
ga_komal_m= 'sound/GA_K.wav'
ma_sudh_m= 'sound/MA.wav'
ma_tivra_m= 'sound/MA_T.wav'
pa_sudh_m= 'sound/PA.wav'
dh_sudh_m= 'sound/DHA.wav'
dh_komal_m= 'sound/DHA_k.wav'
ni_sudh_m = 'sound/NI.wav'
ni_komal_m = 'sound/NI_K.wav'

sa_sudh_h = 'sound/HSA.wav'
re_sudh_h = 'sound/HRE.wav'
re_komal_h = 'sound/HRE_K.wav'
ga_sudh_h = 'sound/HGA.wav'
ga_komal_h = 'sound/HGA_K.wav'
ma_sudh_h = 'sound/HMA.wav'
ma_tivra_h = 'sound/HMA_T.wav'
pa_sudh_h = 'sound/HPA.wav'
dh_sudh_h= 'sound/HDHA.wav'
dh_komal_h = 'sound/HDHA_k.wav'
ni_sudh_h = 'sound/HNI.wav'
ni_komal_h = 'sound/HNI_K.wav'

sa_sudh_l = 'sound/LSA.wav'
re_sudh_l = 'sound/LRE.wav'
re_komal_l = 'sound/LRE_K.wav'
ga_sudh_l = 'sound/LGA.wav'
ga_komal_l = 'sound/LGA_K.wav'
ma_sudh_l = 'sound/LMA.wav'
ma_tivra_l = 'sound/LMA_T.wav'
pa_sudh_l = 'sound/LPA.wav'
dh_sudh_l = 'sound/LDHA.wav'
dh_komal_l = 'sound/LDHA_k.wav'
ni_sudh_l = 'sound/LNI.wav'
ni_komal_l = 'sound/LNI_K.wav'


